### ISSUE TITLE
Error running Setup.ps1

### ISSUE THREAD

**Issue by dboon1978** [PlayFab/MpsAgent#20]
Hey, I'm trying to start up a docker container with your LocalMultiplayerAgent.exe and before running it i'm supposed to run ./Setup.ps1, but I get the following errors:
Creating new subnet 172.19.0.0/16 with gateway 172.19.0.11
Error response from daemon: plugin "nat" not found
Network creation for 172.19.0.0/16 / 172.19.0.11 failed.
Creating new subnet 172.20.0.0/16 with gateway 172.20.0.11
Error response from daemon: plugin "nat" not found
Network creation for 172.20.0.0/16 / 172.20.0.11 failed.
Creating new subnet 172.21.0.0/16 with gateway 172.21.0.11
Error response from daemon: plugin "nat" not found
Network creation for 172.21.0.0/16 / 172.21.0.11 failed.

I looked up the error response and found some comments saying the nat driver has been removed from docker as of 2.2.0.0.  Is there some other way to start this server?

Thanks

**Comment by dgkanatsios** [comment]
Are you using Docker with Windows or Linux containers (it's installed with Linux containers as default)? This error message comes if you are in Linux Containers mode.

**Comment by dboon1978** [comment]
That worked!  It's installing now, thanks!  Is there a tutorial or instructions on how to find the IP of the server when it's running within a playfab title on azure?

**Comment by dgkanatsios** [comment]
Great :)
You get the ip:port details for a server when you allocate it via the RequestMultiplayerServer API, or else you can use the GetMultiplayerServerDetails API to get the same information. You can use the MpsAllocatorSample to easily call these APIs when you are in development stage https://github.com/PlayFab/MpsSamples/tree/master/MpsAllocatorSample

Check our samples' docs here as well: https://docs.microsoft.com/en-us/gaming/playfab/features/multiplayer/servers/mps-allocator-sample

**Comment by dboon1978** [comment]
Amazing, thank you so much for your quick replies!  One last question while I have your attention, not sure if you know anything about the Mirror example, but is there a reason why it's split into a client and server project?  Mirror is supposed to be both in the same project so I'm wondering if its possible to put them back together or if that's something the playfab sdk prevents.

**Comment by dgkanatsios** [comment]
Nope, no particular reason - the original intention was to keep the code separate (client+server implementation) to give emphasis on the GSDK code and its integration with Unity engine. Open to feedback to make it a single project, though :) Do you think that this would help?

**Comment by dboon1978** [comment]
Yeah, I think it would.  Mirror is supposed to run as client/server sharing the same codebase to save on production time.  I originally used the one DapperDino did a tutorial for in youtube, but that version uses an out of date version of Mirror and the playfab sdk, and trying to update seems to require a lot of work.  A similar structure would make a lot of difference.

**Comment by dgkanatsios** [comment]
thanks! Would you mind opening an issue on the MpsSamples repository here? https://github.com/PlayFab/MpsSamples So we can close the issue and continue the discussion there. Much appreciated, thanks!

**Comment by dboon1978** [comment]
Np, i'll close now
